#

---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.10.4
  environments_path: ./.environments

# a VM is created for each platform
platforms:
  #- name: ubuntu-14.04
  - name: centos-6.6 # changed to 6.6 from 6.5 per https://github.com/brianbianco/redisio/issues/182

# a VM is created for each suite
suites:
  - name: spg-db
    provisioner:
      client_rb:
        environment: test
    run_list:
      - recipe[spg-file_edit::insert_line]
      #- recipe[spg-mongodb::setup]
      #- recipe[spg-printer::stack-config]
      #- recipe[spg-monit::install]
      #- recipe[mongodb::install]
      #- recipe[spg-mongodb::default]
      #- recipe[mongodb::replicaset]
    attributes:
